[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-net = "0.2.4"
wasm-bindgen-futures = "0.4.33"
yew = "0.19"
serde = { version = "1.0", features = ["derive"] }
gloo-timers = "0.2.4"
